FROM node:23.3-alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY projects ./projects
COPY tsconfig.json ./
COPY angular.json ./

RUN npm install

RUN npm run build shared
RUN npm run build recommendations

EXPOSE 4002

ENV NODE_ENV=production

WORKDIR /usr/src/app/dist/recommendations/server

CMD [ "node", "server.mjs" ]