FROM node:23.3-alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY projects ./projects
COPY tsconfig.json ./
COPY angular.json ./

RUN npm install

RUN npm run build shared
RUN npm run build homepage

EXPOSE 4003

# ENV NODE_ENV=production

WORKDIR /usr/src/app/dist/homepage/server

CMD [ "node", "server.mjs" ]