FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY projects ./projects
COPY tsconfig.json ./
COPY angular.json ./

RUN npm install

RUN npm run build shared
RUN npm run build teasers

EXPOSE 4001

ENV NODE_ENV=production

WORKDIR /usr/src/app/dist/teasers/server

CMD [ "node", "server.mjs" ]