services:
  mfe-cdn:
    build:
      context: ./mfe/cdn
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  monolith:
    build:
      context: ./monolith
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 4G

networks:
  app-network:
    driver: bridge