services:
  cdn:
    container_name: cdn
    build:
      context: ./mfe/cdn
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  monolith:
    container_name: monolith
    build:
      context: ./monolith
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 4G

  cadvisor:
    # https://github.com/google/cadvisor/issues/2838
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    privileged: true
    ports:
      - "3001:3001"
    command:
      - --port=3001
      - --allow_dynamic_housekeeping=true 
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
    restart: unless-stopped
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "3002:3002"
    volumes: 
      - "./prometheus.yml:/prometheus/prometheus.yml"
    command:
      - --config.file=/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=1h
      - --web.listen-address=:3002
      - --web.enable-lifecycle
      - --enable-feature=memory-snapshot-on-shutdown
    depends_on:
      - cadvisor