global:
  scrape_interval: 1s    
  evaluation_interval: 1s  
  scrape_timeout: 500ms  

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:3001"]